# Generated by Django 5.2.4 on 2025-07-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='datecompleted',
        ),
    ]
