# Generated by Django 5.2.4 on 2025-07-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
